# Generated by Django 3.2.6 on 2021-09-14 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_alter_devicemodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicemodel',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Модель'),
        ),
    ]
