# Generated by Django 3.2.6 on 2021-09-14 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_alter_devicemodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicemodel',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='devices.devicetype', verbose_name='Тип устройства'),
        ),
    ]
