# Generated by Django 3.2.6 on 2021-08-20 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('directory', '0005_customer'),
        ('devices', '0002_alter_devicemodel_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(verbose_name='Дата/Время')),
                ('equipment', models.CharField(max_length=255, verbose_name='В комплекте')),
                ('defect', models.CharField(max_length=255, verbose_name='Неисправность')),
                ('appearance', models.CharField(max_length=255, verbose_name='Внешний вид')),
                ('inspection', models.CharField(max_length=255, verbose_name='Предварительный осмотр')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directory.customer', verbose_name='Клиент')),
                ('device_model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='devices.devicemodel', verbose_name='Модель')),
                ('device_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='devices.devicetype', verbose_name='Устройство')),
            ],
            options={
                'verbose_name': 'Заявка на ремонт',
                'verbose_name_plural': 'Заявки на ремонт',
            },
        ),
    ]
