# Generated by Django 3.2.6 on 2021-08-21 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'Диагностика'), (2, 'Согласование'), (3, 'Ремонт'), (4, 'Готов'), (5, 'Выдан')], default=1, max_length=9, verbose_name='Статус'),
        ),
    ]
