# Generated by Django 3.2.6 on 2021-08-21 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0005_customer'),
        ('orders', '0002_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.CharField(default='', max_length=1024, verbose_name='Заметки'),
        ),
        migrations.AddField(
            model_name='order',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='directory.employee', verbose_name='Исполнитель'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'Диагностика'), (2, 'Согласование'), (3, 'Ремонт'), (4, 'Готов'), (5, 'Выдан'), (6, 'Архив')], default=1, verbose_name='Статус'),
        ),
    ]
