# Generated by Django 3.2.6 on 2021-08-23 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20210821_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='Заметки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='equipment',
            field=models.CharField(max_length=255, null=True, verbose_name='В комплекте'),
        ),
    ]
