# Generated by Django 3.2.6 on 2021-08-23 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20210823_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='equipment',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='В комплекте'),
        ),
    ]
