# Generated by Django 3.2.4 on 2021-09-02 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_equipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='notified',
            field=models.BooleanField(default=False, verbose_name='Уведомлен'),
        ),
    ]
