# Generated by Django 3.2.4 on 2021-09-02 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_order_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='serial',
            field=models.CharField(default='б/н', max_length=25, verbose_name='Серийный номер'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'Диагностика'), (2, 'Согласование'), (3, 'Ремонт'), (4, 'Готов'), (5, 'Выдан'), (6, 'Архив'), (7, 'Отказ от ремонта')], default=1, verbose_name='Статус'),
        ),
    ]
