# Generated by Django 3.2.6 on 2021-09-16 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_order_device_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='notes',
            field=models.TextField(max_length=1048, null=True, verbose_name='Заметки'),
        ),
        migrations.AddField(
            model_name='order',
            name='zip_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Стоимость запчастей'),
        ),
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=300, max_digits=10, verbose_name='Стоимость'),
        ),
    ]
