# Generated by Django 3.2.6 on 2021-09-16 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20210916_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='notes',
            field=models.TextField(blank=True, max_length=1048, null=True, verbose_name='Заметки'),
        ),
    ]
