# Generated by Django 3.2.6 on 2021-09-16 17:47

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_alter_order_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='notes',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Заметки'),
        ),
    ]
