# Generated by Django 3.2.6 on 2021-09-16 18:27

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_alter_order_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='notes',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Заметки'),
        ),
    ]
